# Generated by Django 5.2.5 on 2025-08-24 16:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Survey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(auto_now_add=True)),
                ("sleep_hours", models.IntegerField(blank=True, null=True)),
                ("energy", models.IntegerField(blank=True, null=True)),
                ("ate_breakfast", models.BooleanField(blank=True, null=True)),
                ("water_glasses", models.IntegerField(blank=True, null=True)),
                ("activity_minutes", models.IntegerField(blank=True, null=True)),
                ("stress_level", models.IntegerField(blank=True, null=True)),
                ("screen_time", models.BooleanField(blank=True, null=True)),
                ("mood", models.IntegerField(blank=True, null=True)),
                ("smoked_or_drink", models.BooleanField(blank=True, null=True)),
                ("work_hours", models.IntegerField(blank=True, null=True)),
                ("pain", models.BooleanField(blank=True, null=True)),
                ("pain_notes", models.TextField(blank=True, null=True)),
                (
                    "weather_effect",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="surveys",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
