# Generated by Django 5.2.5 on 2025-08-26 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_survey"),
    ]

    operations = [
        migrations.AddField(
            model_name="survey",
            name="recommendation",
            field=models.TextField(blank=True, null=True),
        ),
    ]
