# Generated by Django 5.2.4 on 2025-09-01 17:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Survey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sleep_hours", models.FloatField(default=0)),
                ("ate_breakfast", models.BooleanField(default=False)),
                ("water_glasses", models.IntegerField(default=0)),
                ("activity_minutes", models.IntegerField(default=0)),
                ("stress_level", models.IntegerField(default=0)),
                ("screen_time", models.FloatField(default=0)),
                ("mood", models.IntegerField(default=3)),
                ("smoked_or_drink", models.BooleanField(default=False)),
                ("work_hours", models.IntegerField(default=0)),
                ("pain", models.BooleanField(default=False)),
                ("recommendation", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="surveys",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
